# Generated by Django 5.2.17 on 2026-09-30 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingest", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="boot_id",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="device",
            name="last_sequence",
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="safetyevent",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ingest.inboundmessage"
            ),
        ),
    ]
