#!/usr/bin/env python3
"""Generate docs/configuration.md from firmware/components/rb_config/Kconfig.

    python3 tools/diagnostics/kconfig_doc.py > docs/configuration.md

Keeps the configuration reference in sync with the one place the options are
defined. Only the small Kconfig subset used there is supported (menu, config,
choice, bool/int/hex/string, default, range, depends on, help).
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
KCONFIG = ROOT / "firmware" / "components" / "rb_config" / "Kconfig"
FLAGS = ("UNCONFIRMED", "OPEN QUESTION", "UNVERIFIED")


def parse(lines):
    menus = []            # stack of titles
    sections = {}         # title path -> list of entries
    order = []
    entry = None
    in_help = False
    help_indent = 0

    def finish():
        nonlocal entry
        if entry is not None:
            key = " → ".join(menus)
            if key not in sections:
                sections[key] = []
                order.append(key)
            sections[key].append(entry)
            entry = None

    for raw in lines:
        line = raw.rstrip("\n")
        stripped = line.strip()
        indent = len(line) - len(line.lstrip())
        if in_help:
            if stripped and indent < help_indent:
                in_help = False
            else:
                if entry is not None:
                    entry["help"] += " " + stripped
                continue
        if not stripped or stripped.startswith("#"):
            continue
        if stripped.startswith("menu "):
            finish()
            menus.append(re.match(r'menu\s+"(.*)"', stripped).group(1))
            continue
        if stripped == "endmenu":
            finish()
            menus.pop()
            continue
        if stripped.startswith("choice"):
            finish()
            entry = {"name": stripped.split()[1], "type": "choice", "prompt": "", "default": "", "range": "",
                     "help": "", "options": []}
            continue
        if stripped == "endchoice":
            finish()
            continue
        if stripped.startswith("config "):
            name = stripped.split()[1]
            if entry is not None and entry["type"] == "choice":
                entry["options"].append([name, ""])
                entry["_last_option"] = True
                continue
            finish()
            entry = {"name": name, "type": "", "prompt": "", "default": "", "range": "", "help": ""}
            continue
        if entry is None:
            continue
        m = re.match(r'(bool|int|hex|string)\s+"(.*)"', stripped)
        if m:
            if entry["type"] == "choice" and entry.get("_last_option"):
                entry["options"][-1][1] = m.group(2)
            else:
                entry["type"], entry["prompt"] = m.group(1), m.group(2)
            continue
        if stripped.startswith("prompt "):
            entry["prompt"] = re.match(r'prompt\s+"(.*)"', stripped).group(1)
            continue
        if stripped.startswith("default ") and not entry["default"]:
            entry["default"] = stripped[len("default "):]
            continue
        if stripped.startswith("range "):
            entry["range"] = stripped[len("range "):].replace(" ", " – ")
            continue
        if stripped == "help":
            in_help = True
            help_indent = indent + 1
            continue
    finish()
    return order, sections


def main():
    order, sections = parse(KCONFIG.read_text().splitlines(True))
    out = [
        "# Configuration reference (TODO section 26)",
        "",
        "Generated by `tools/diagnostics/kconfig_doc.py` from",
        "[`firmware/components/rb_config/Kconfig`](../firmware/components/rb_config/Kconfig),",
        "which is the one place every tunable is defined. Change values with",
        "`idf.py menuconfig` → **RB4107 configuration**, or per project in `sdkconfig.defaults`.",
        "Items flagged ⚠ have not been confirmed on hardware or are open questions (TODO section 32).",
        "",
    ]
    for key in order:
        title = key.replace("RB4107 configuration → ", "") or "General"
        if title == "RB4107 configuration":
            continue
        out += [f"## {title}", "", "| Option | Description | Default | Range | |", "|---|---|---|---|---|"]
        for e in sections[key]:
            flag = "⚠" if any(f in e["help"] for f in FLAGS) else ""
            desc = e["prompt"]
            if e["type"] == "choice":
                desc += ": " + "; ".join(f"`CONFIG_{n}` = {p}" for n, p in e["options"])
            default = f"CONFIG_{e['default']}" if e["type"] == "choice" else e["default"]
            name = f"`{e['name']}` (choice)" if e["type"] == "choice" else f"`CONFIG_{e['name']}`"
            out.append(f"| {name} | {desc} | `{default}` | {e['range']} | {flag} |")
        out.append("")
    sys.stdout.write("\n".join(out))


if __name__ == "__main__":
    main()
