# Generated by Django 5.2.17 on 2026-09-29 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=128, unique=True)),
                ('latest', models.JSONField(default=dict)),
                ('field_updated_at', models.JSONField(default=dict)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_received_at', models.DateTimeField(blank=True, null=True)),
                ('last_snapshot_source_at', models.DateTimeField(blank=True, null=True)),
                ('reported_online', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='mqtt', max_length=80, unique=True)),
                ('connected', models.BooleanField(default=False)),
                ('heartbeat_at', models.DateTimeField(null=True)),
                ('last_message_at', models.DateTimeField(null=True)),
                ('error', models.TextField(blank=True)),
                ('mode', models.CharField(default='mqtt', max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='InboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('received_at', models.DateTimeField(db_index=True)),
                ('source_at', models.DateTimeField(null=True)),
                ('topic', models.CharField(max_length=1024)),
                ('raw', models.TextField()),
                ('retained', models.BooleanField(default=False)),
                ('qos', models.PositiveSmallIntegerField(default=0)),
                ('outcome', models.CharField(db_index=True, default='accepted', max_length=24)),
                ('error', models.TextField(blank=True)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingest.device')),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField()),
                ('source_at', models.DateTimeField(null=True)),
                ('values', models.JSONField(default=dict)),
                ('temperature_c', models.FloatField(null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingest.device')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ingest.inboundmessage')),
            ],
            options={
                'indexes': [models.Index(fields=['device', 'received_at'], name='ingest_read_device__6c72b3_idx')],
            },
        ),
        migrations.CreateModel(
            name='SafetyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField()),
                ('source_at', models.DateTimeField(null=True)),
                ('event_type', models.CharField(max_length=80)),
                ('detail', models.JSONField(default=dict)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingest.device')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ingest.inboundmessage')),
            ],
            options={
                'indexes': [models.Index(fields=['device', 'received_at'], name='ingest_safe_device__ee7845_idx')],
            },
        ),
    ]
