# Generated by Django 5.2.17 on 2026-10-02 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingest", "0002_boot_tracking"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThermalFrame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sensor_node", models.CharField(max_length=32)),
                ("received_at", models.DateTimeField()),
                ("source_at", models.DateTimeField(null=True)),
                ("frame", models.JSONField(default=dict)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ingest.device"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("device", "sensor_node"), name="one_frame_per_node"
                    )
                ],
            },
        ),
    ]
