# Generated by Django 5.2.18 on 2026-10-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingest", "0003_thermal_frame"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="inboundmessage",
            index=models.Index(
                fields=["device", "topic", "received_at"],
                name="inbound_device_topic_received",
            ),
        ),
    ]
