#pragma once

#include "driver/gpio.h"

#define WARNING_DELAY_MS 60000U
#define SHUTDOWN_DELAY_MS 90000U
#define SENSOR_TIMEOUT_MS 5000U
#define TELEMETRY_INTERVAL_MS 10000U

#define W5500_INT_GPIO GPIO_NUM_12
#define W5500_MOSI_GPIO GPIO_NUM_13
#define W5500_MISO_GPIO GPIO_NUM_14
#define W5500_SCLK_GPIO GPIO_NUM_15
#define W5500_CS_GPIO GPIO_NUM_16

#define RS485_TX_GPIO GPIO_NUM_17
#define RS485_RX_GPIO GPIO_NUM_18
#define RGB_LED_GPIO GPIO_NUM_38
#define RTC_INT_GPIO GPIO_NUM_40
#define I2C_SCL_GPIO GPIO_NUM_41
#define I2C_SDA_GPIO GPIO_NUM_42
#define UART_TX_GPIO GPIO_NUM_43
#define UART_RX_GPIO GPIO_NUM_44
#define TF_MISO_GPIO GPIO_NUM_45
#define BUZZER_GPIO GPIO_NUM_46
#define TF_MOSI_GPIO GPIO_NUM_47
#define TF_SCLK_GPIO GPIO_NUM_48
#define BOOT_GPIO GPIO_NUM_0

#define TCA9554_I2C_PORT I2C_NUM_0
#define TCA9554_I2C_ADDRESS 0x20
#define TCA9554_ACTIVE_LEVEL 1
#define PCF85063_I2C_ADDRESS 0x51
#define RELAY_ACTIVE_LEVEL 1
#define BUZZER_ACTIVE_LEVEL 1

#define WIFI_ENABLE 1
#define NETWORK_ENABLE WIFI_ENABLE
#define SENSOR_NODE_ENABLE 1
#define MQTT_ENABLE 1
#define MQTT_BROKER_URI "mqtt://CHANGE_ME"

#define MQTT_TOPIC_STATUS "system/status"
#define MQTT_TOPIC_SENSORS "system/sensors"
#define MQTT_TOPIC_ALARM "system/alarm"

#define RELAY_COUNT 8